; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-atoms3]
platform = espressif32
board = m5stack-atoms3
framework = arduino
build_flags =
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
	-DCORE_DEBUG_LEVEL=4
	-DMQTT_MAX_PACKET_SIZE=1024
lib_deps = 
	m5stack/M5Unified@=0.1.16
	m5stack/M5AtomS3@^1.0.0
	fastled/FastLED@^3.9.14
	knolleary/PubSubClient@^2.8
	vshymanskyy/StreamDebugger@^1.0.1
	https://github.com/anthony-blynk/TinyGSM-SIM7028-Frozen.git
	; https://github.com/m5stack/TinyGSM/archive/refs/tags/v0.12.0-patch-1.zip
	arduino-libraries/ArduinoHttpClient@^0.6.0
	; bakercp/CRC32@^2.0.0
	4-20ma/ModbusMaster
upload_speed = 115200
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time